language: node_js
sudo: false
node_js:
  - "4.1"
  - "5"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
services:
  - mongodb
env:
  - TRAVIS=travis CXX=g++-4.8

after_success:
- npm run coveralls
